import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import Adminsidebar from "@/components/Adminsidebar";
import AdminHeader from "@/components/AdminHeader";

export const metadata: Metadata = {
  title: "Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          <div className="flex flex-col md:flex-row min-h-screen bg-[#eff6f9]">
            <Adminsidebar />
            <div className="flex flex-col flex-1 bg-[#eff6f9]">
              <AdminHeader
                breadcrumb="Super Admin / Portal"
                // title="Add Student"
              />
              {children}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
